
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4201"